/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.trs.bt.windows;

import com.trs.bt.providers.ComponentTransporter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.trs.bt.windows//ExplorerTreeMonitor//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ExplorerTreeMonitorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.trs.bt.windows.ExplorerTreeMonitorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ExplorerTreeMonitorAction",
        preferredID = "ExplorerTreeMonitorTopComponent"
)
@Messages({
    "CTL_ExplorerTreeMonitorAction=ExplorerTreeMonitor",
    "CTL_ExplorerTreeMonitorTopComponent=ExplorerTreeMonitor Window",
    "HINT_ExplorerTreeMonitorTopComponent=This is a ExplorerTreeMonitor window"
})
public final class ExplorerTreeMonitorTopComponent extends TopComponent {
    DefaultMutableTreeNode treeNodeRoot;
    private final ComponentTransporter componentTransporter;
    public ExplorerTreeMonitorTopComponent() {
        initComponents();
        setName(Bundle.CTL_ExplorerTreeMonitorTopComponent());
        setToolTipText(Bundle.HINT_ExplorerTreeMonitorTopComponent());
        componentTransporter=ComponentTransporter.getComponentTransporter();
        componentTransporter.setTopComponentExplorerTreeMonitor(this);
        treeIpAddress.setName("MYJTREE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeIpAddress = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeIpAddress.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeIpAddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeIpAddress;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        treeNodeRoot = new DefaultMutableTreeNode("Ip Adresi");
//        DefaultMutableTreeNode ip1
//                = new DefaultMutableTreeNode(" asd");
//        DefaultMutableTreeNode ip2
//                = new DefaultMutableTreeNode(" asd");
//        treeNodeRoot.add(ip1);
//        treeNodeRoot.add(ip2);
        DefaultTreeModel defaultTreeModel = new DefaultTreeModel(treeNodeRoot);
        treeIpAddress.setModel(defaultTreeModel);
        this.setVisible(true);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
//    public void transportMe(String s){
//        treeNodeRoot.add(treeNodeRoot);
//    }
}
